# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace  # Loại bỏ khoảng trắng thừa cuối dòng
    -   id: end-of-file-fixer  # Đảm bảo file kết thúc bằng một dòng mới
    -   id: check-yaml  # Kiểm tra cú pháp file YAML
    -   id: check-json  # Kiểm tra cú pháp file JSON
    -   id: check-added-large-files  # Ngăn commit file quá lớn
    -   id: check-merge-conflict  # Kiểm tra xung đột merge
    -   id: detect-private-key  # Phát hiện private key bị commit
    -   id: check-ast  # Kiểm tra Python syntax
    -   id: debug-statements  # Phát hiện câu lệnh debug như pdb/ipdb

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort  # Sắp xếp import

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy  # Kiểm tra kiểu dữ liệu tĩnh
        additional_dependencies: [
            'types-requests',
            'types-PyYAML',
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade  # Tự động nâng cấp cú pháp Python
        args: [--py38-plus]  # Chỉnh sửa theo phiên bản Python của bạn

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
